### ISSUE TITLE
Add back button on introductory story pages

### ISSUE THREAD

**Issue by VictoriaLemons** [luceroweb/haunted-house-game#93]
### Devices
Device name	DESKTOP-VRJKTUH
Processor	AMD Ryzen 7 3700X 8-Core Processor 3.59 GHz
System type	64-bit operating system, x64-based processor

Windows 10 Home 21H1

Google Chrome - Version 93.0.4577.63 (Official Build) (64-bit)

###Description

### Expected Behavior
user is able to review previous pages for memory refresh or accidental forward click

### Actual Behavior
Start Game pages 1-2 and Hallway pages 1-4 have no button to review previous pages; Hallway 5 cannot review the story after "skip to gameplay"

### Steps to Reproduce Issue
1. go to site
2. click ""continue story""
3. observe pages 1-2 and 1-4 have no backwards feature
OR
2. click ""skip to gameplay"" 
3. observe Hallway has no ""review story"" feature

**Comment by alberme** [comment]
@VictoriaLemons thank you for your suggestion but I will have to reject due to time constraints and how the story is intended to flow forward and linear. additionally, the "skip to gameplay" button is for users that want to play again without having to speed click through the story pages.

cc: @lreyes-qae @luceroweb
